### ISSUE TITLE
Saving and sharing states

### ISSUE THREAD

**Issue by blankdots** [NBISweden/rke-openstack#13]
### Description
Liisa might already have requested this, but I am putting it an issue so we can track it.
Would like to save the state of the terraform setup, `kube_config_cluster.yml` as well as the `terraform.tfvars` in an object storage or in a remote location so that those can be retrieved, by collaborators on the same project.

### Proposed solution
One possible solution would be: https://www.terraform.io/docs/backends/types/swift.html
But any object storage might work as well.
Maybe this offers a potential solution: https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/terraformUsingObjectStore.htm (although looks like OracleCloud specific)

### Definition of Done
Being able to save and retrieve state as well as share these among collaborators

**Comment by jonandernovella** [comment]
We tested this feature with the `s3` backend and it seems to work well. Find pasted below some sample settings:

```
 terraform {
  backend "s3" {
    access_key = "xyz"
    secret_key = "xyz"
    region = "us-west-1"
    bucket = "test"
    endpoint = "https://s3.backend.net"
    key = "terraform.tfstate"
    skip_requesting_account_id = true
    skip_credentials_validation = true
    skip_get_ec2_platforms = true
    skip_metadata_api_check = true
    skip_region_validation = true
  }
}```

**Comment by blankdots** [comment]
LGTM, can we have a PR about it ?

**Comment by blankdots** [comment]
for swift it is something like:
```
terraform {
  backend "swift" {
    container               = "cluster-state"
    archive_container  = "cluster-state-archive"
  }
}
```
